export const category = [
  { id: 1, catName: "Programming Language" },
  { id: 2, catName: "Framework" },
  { id: 3, catName: "Soft Skills" },
  { id: 4, catName: "Database" },
  { id: 5, catName: "Data Analytics" },
  { id: 6, catName: "Security" },
  { id: 7, catName: "Microsoft" },
];

export const catalog = [
  {
    title: "Basic Excel",
    category: "Microsoft",
    time: "10 Minutes",
    format: "MCQs",
    link: "/assessment/basic-excel",
  },
  {
    title: "Basic PowerPoint",
    category: "Microsoft",
    time: "10 Minutes",
    format: "MCQs",
    link: "/assessment/basic-powerpoint",
  },
  {
    title: "Digital Marketing",
    category: "Digital Marketing",
    time: "10 Minutes",
    format: "MCQs",
    link: "/assessment/digital-marketing",
  },
  {
    title: "Generative AI",
    category: "AI",
    time: "10 Minutes",
    format: "MCQs",
    link: "/assessment/generative-ai",
  },
  {
    title: "Hibernate Assessment",
    category: "Framework",
    time: "10 Minutes",
    format: "MCQs",
    link: "/assessment/hibernate",
  },
  {
    title: "Spring Assessment",
    category: "Framework",
    time: "10 Minutes",
    format: "MCQs",
    link: "/assessment/spring",
  },
  {
    title: "Django Assessment",
    category: "Framework",
    time: "10 Minutes",
    format: "MCQs",
    link: "/assessment/django",
  },
  {
    title: "Flask Assessment",
    category: "Framework",
    time: "10 Minutes",
    format: "MCQs",
    link: "/assessment/flask",
  },
  {
    title: "Ember.js Assessment",
    category: "Framework",
    time: "10 Minutes",
    format: "MCQs",
    link: "/assessment/emberjs",
  },
  {
    title: "Backbone.js Assessment",
    category: "Framework",
    time: "10 Minutes",
    format: "MCQs",
    link: "/assessment/backbonejs",
  },
  {
    title: "Polymer Assessment",
    category: "Framework",
    time: "10 Minutes",
    format: "MCQs",
    link: "/assessment/polymer",
  },
  {
    title: "Aurelia Assessment",
    category: "Framework",
    time: "10 Minutes",
    format: "MCQs",
    link: "/assessment/aurelia",
  },
  {
    title: "Meteor Assessment",
    category: "Framework",
    time: "10 Minutes",
    format: "MCQs",
    link: "/assessment/meteor",
  },
  {
    title: "jQuery Assessment",
    category: "Framework",
    time: "10 Minutes",
    format: "MCQs",
    link: "/assessment/jquery",
  },
  {
    title: "Go Assessment",
    category: "Programming Language",
    time: "10 Minutes",
    format: "MCQs",
    link: "/assessment/golang",
  },
  {
    title: "C# Assessment",
    category: "Programming Language",
    time: "10 Minutes",
    format: "MCQs",
    link: "/assessment/csharp",
  },
  {
    title: "Swift Assessment",
    category: "Programming Language",
    time: "10 Minutes",
    format: "MCQs",
    link: "/assessment/swift",
  },
  {
    title: "R Programming Assessment",
    category: "Programming Language",
    time: "10 Minutes",
    format: "MCQs",
    link: "/assessment/r",
  },
  {
    title: "Ruby Assessment",
    category: "Programming Language",
    time: "10 Minutes",
    format: "MCQs",
    link: "/assessment/ruby",
  },
  {
    title: "MATLAB Assessment",
    category: "Programming Language",
    time: "10 Minutes",
    format: "MCQs",
    link: "/assessment/matlab",
  },
  {
    title: "TypeScript Assessment",
    category: "Programming Languages",
    time: "10 Minutes",
    format: "MCQs",
    link: "/assessment/typescript",
  },
  {
    title: "Scala Assessment",
    category: "Programming Language",
    time: "10 Minutes",
    format: "MCQs",
    link: "/assessment/scala",
  },
  {
    title: "SQL Assessment",
    category: "Programming Language",
    time: "10 Minutes",
    format: "MCQs",
    link: "/assessment/sql",
  },
  {
    title: "NoSQL Assessment",
    category: "Programming Language",
    time: "10 Minutes",
    format: "MCQs",
    link: "/assessment/nosql",
  },
  {
    title: "Rust Programming Assessment",
    category: "Programming Language",
    time: "10 Minutes",
    format: "MCQs",
    link: "/assessment/rust",
  },
  {
    title: "Perl Programming Assessment",
    category: "Programming Language",
    time: "10 Minutes",
    format: "MCQs",
    link: "/assessment/perl",
  },
  {
    title: "C++ Assessment",
    category: "Programming Language",
    time: "10 Minutes",
    format: "MCQs",
    link: "/assessment/cplusplus",
  },
  {
    title: "MongoDB Assessment",
    category: "Database",
    time: "10 Minutes",
    format: "MCQs",
    link: "/assessment/mongodb",
  },
  {
    title: "English Language",
    category: "Soft Skills",
    time: "10 Minutes",
    format: "MCQs",
    link: "/assessment/english-language",
  },
  {
    title: "JavaScript Assessment",
    category: "Programming Language",
    time: "10 Minutes",
    format: "MCQs",
    link: "/assessment/javascript",
  },
  {
    title: "Python Assessment",
    category: "Programming Language",
    time: "10 Minutes",
    format: "MCQs",
    link: "/assessment/python",
  },
  {
    title: "Java Assessment",
    category: "Programming Language",
    time: "10 Minutes",
    format: "MCQs",
    link: "/assessment/java",
  },

  {
    title: "React.js Assessment",
    category: "Framework",
    time: "10 Minutes",
    format: "MCQs",
    link: "/assessment/reactjs",
  },
  {
    title: "Node.js Assessment",
    category: "Framework",
    time: "10 Minutes",
    format: "MCQs",
    link: "/assessment/nodejs",
  },
  {
    title: "Angular.js Assessment",
    category: "Framework",
    time: "10 Minutes",
    format: "MCQs",
    link: "/assessment/angularjs",
  },
  {
    title: "Vue.js Assessment",
    category: "Framework",
    time: "10 Minutes",
    format: "MCQs",
    link: "/assessment/vuejs",
  },
  {
    title: "RDBMS Assessment",
    category: "Database",
    time: "10 Minutes",
    format: "MCQs",
    link: "/assessment/rdbms",
  },
  {
    title: "Negotiation Attitude",
    category: "Soft Skills",
    time: "10 Minutes",
    format: "MCQs",
    link: "/assessment/negotiation-attitude",
  },
  {
    title: "Data Analytics",
    category: "Data Analytics",
    time: "10 Minutes",
    format: "MCQs",
    link: "/assessment/data-analytics",
  },
  {
    title: "Cyber Security",
    category: "Security",
    time: "10 Minutes",
    format: "MCQs",
    link: "/assessment/cybersecurity",
  },
];
