export const category = [
  { id: 1, catName: "Programming Language" },
  { id: 2, catName: "Framework" },
  { id: 3, catName: "Soft Skills" },
  { id: 4, catName: "Database" },
  { id: 5, catName: "Data Analytics" },
  { id: 6, catName: "Security" },
  { id: 7, catName: "Microsoft" },
];

export const catalog = [
  {
    id: 1,
    title: "Basic Excel",
    category: "Microsoft",
    time: "10 Minutes",
    format: "MCQs",
    link: "/assessment/basic-excel",
  },
  {
    id: 2,
    title: "Basic PowerPoint",
    category: "Microsoft",
    time: "10 Minutes",
    format: "MCQs",
    link: "/assessment/basic-powerpoint",
  },
  {
    id: 3,
    title: "Digital Marketing",
    category: "Digital Marketing",
    time: "10 Minutes",
    format: "MCQs",
    link: "/assessment/digital-marketing",
  },
  {
    id: 4,
    title: "Generative AI",
    category: "AI",
    time: "10 Minutes",
    format: "MCQs",
    link: "/assessment/generative-ai",
  },
  {
    id: 5,
    title: "Hibernate Assessment",
    category: "Framework",
    time: "10 Minutes",
    format: "MCQs",
    link: "/assessment/hibernate",
  },
  {
    id: 6,
    title: "Spring Assessment",
    category: "Framework",
    time: "10 Minutes",
    format: "MCQs",
    link: "/assessment/spring",
  },
  {
    id: 7,
    title: "Django Assessment",
    category: "Framework",
    time: "10 Minutes",
    format: "MCQs",
    link: "/assessment/django",
  },
  {
    id: 8,
    title: "Flask Assessment",
    category: "Framework",
    time: "10 Minutes",
    format: "MCQs",
    link: "/assessment/flask",
  },
  {
    id: 9,
    title: "Ember.js Assessment",
    category: "Framework",
    time: "10 Minutes",
    format: "MCQs",
    link: "/assessment/emberjs",
  },
  {
    id: 10,
    title: "Backbone.js Assessment",
    category: "Framework",
    time: "10 Minutes",
    format: "MCQs",
    link: "/assessment/backbonejs",
  },
  {
    id: 11,
    title: "Polymer Assessment",
    category: "Framework",
    time: "10 Minutes",
    format: "MCQs",
    link: "/assessment/polymer",
  },
  {
    id: 12,
    title: "Aurelia Assessment",
    category: "Framework",
    time: "10 Minutes",
    format: "MCQs",
    link: "/assessment/aurelia",
  },
  {
    id: 13,
    title: "Meteor Assessment",
    category: "Framework",
    time: "10 Minutes",
    format: "MCQs",
    link: "/assessment/meteor",
  },
  {
    id: 14,
    title: "jQuery Assessment",
    category: "Framework",
    time: "10 Minutes",
    format: "MCQs",
    link: "/assessment/jquery",
  },
  {
    id: 15,
    title: "Go Assessment",
    category: "Programming Language",
    time: "10 Minutes",
    format: "MCQs",
    link: "/assessment/golang",
  },
  {
    id: 16,
    title: "C# Assessment",
    category: "Programming Language",
    time: "10 Minutes",
    format: "MCQs",
    link: "/assessment/csharp",
  },
  {
    id: 17,
    title: "Swift Assessment",
    category: "Programming Language",
    time: "10 Minutes",
    format: "MCQs",
    link: "/assessment/swift",
  },
  {
    id: 18,
    title: "R Programming Assessment",
    category: "Programming Language",
    time: "10 Minutes",
    format: "MCQs",
    link: "/assessment/r",
  },
  {
    id: 19,
    title: "Ruby Assessment",
    category: "Programming Language",
    time: "10 Minutes",
    format: "MCQs",
    link: "/assessment/ruby",
  },
  {
    id: 20,
    title: "MATLAB Assessment",
    category: "Programming Language",
    time: "10 Minutes",
    format: "MCQs",
    link: "/assessment/matlab",
  },
  {
    id: 21,
    title: "TypeScript Assessment",
    category: "Programming Languages",
    time: "10 Minutes",
    format: "MCQs",
    link: "/assessment/typescript",
  },
  {
    id: 22,
    title: "Scala Assessment",
    category: "Programming Language",
    time: "10 Minutes",
    format: "MCQs",
    link: "/assessment/scala",
  },
  {
    id: 23,
    title: "SQL Assessment",
    category: "Programming Language",
    time: "10 Minutes",
    format: "MCQs",
    link: "/assessment/sql",
  },
  {
    id: 24,
    title: "NoSQL Assessment",
    category: "Programming Language",
    time: "10 Minutes",
    format: "MCQs",
    link: "/assessment/nosql",
  },
  {
    id: 25,
    title: "Rust Programming Assessment",
    category: "Programming Language",
    time: "10 Minutes",
    format: "MCQs",
    link: "/assessment/rust",
  },
  {
    id: 26,
    title: "Perl Programming Assessment",
    category: "Programming Language",
    time: "10 Minutes",
    format: "MCQs",
    link: "/assessment/perl",
  },
  {
    id: 27,
    title: "C++ Assessment",
    category: "Programming Language",
    time: "10 Minutes",
    format: "MCQs",
    link: "/assessment/cplusplus",
  },
  {
    id: 28,
    title: "MongoDB Assessment",
    category: "Database",
    time: "10 Minutes",
    format: "MCQs",
    link: "/assessment/mongodb",
  },
  {
    id: 29,
    title: "English Language",
    category: "Soft Skills",
    time: "10 Minutes",
    format: "MCQs",
    link: "/assessment/english-language",
  },
  {
    id: 30,
    title: "JavaScript Assessment",
    category: "Programming Language",
    time: "10 Minutes",
    format: "MCQs",
    link: "/assessment/javascript",
  },
  {
    id: 31,
    title: "Python Assessment",
    category: "Programming Language",
    time: "10 Minutes",
    format: "MCQs",
    link: "/assessment/python",
  },
  {
    id: 32,
    title: "Java Assessment",
    category: "Programming Language",
    time: "10 Minutes",
    format: "MCQs",
    link: "/assessment/java",
  },
  {
    id: 33,
    title: "React.js Assessment",
    category: "Framework",
    time: "10 Minutes",
    format: "MCQs",
    link: "/assessment/reactjs",
  },
  {
    id: 34,
    title: "Node.js Assessment",
    category: "Framework",
    time: "10 Minutes",
    format: "MCQs",
    link: "/assessment/nodejs",
  },
  {
    id: 35,
    title: "Angular.js Assessment",
    category: "Framework",
    time: "10 Minutes",
    format: "MCQs",
    link: "/assessment/angularjs",
  },
  {
    id: 36,
    title: "Vue.js Assessment",
    category: "Framework",
    time: "10 Minutes",
    format: "MCQs",
    link: "/assessment/vuejs",
  },
  {
    id: 37,
    title: "RDBMS Assessment",
    category: "Database",
    time: "10 Minutes",
    format: "MCQs",
    link: "/assessment/rdbms",
  },
  {
    id: 38,
    title: "Negotiation Attitude",
    category: "Soft Skills",
    time: "10 Minutes",
    format: "MCQs",
    link: "/assessment/negotiation-attitude",
  },
  {
    id: 39,
    title: "Data Analytics",
    category: "Data Analytics",
    time: "10 Minutes",
    format: "MCQs",
    link: "/assessment/data-analytics",
  },
  {
    id: 40,
    title: "Cyber Security",
    category: "Security",
    time: "10 Minutes",
    format: "MCQs",
    link: "/assessment/cybersecurity",
  },
  {
    id: 41,
    title: "Artificial Intelligence",
    category: "Artificial Intelligence",
    time: "10 Minutes",
    format: "MCQs",
    link: "/assessment/artificial-intelligence",
  },
  {
    id: 42,
    title: "Machine Learning",
    category: "Machine Learning",
    time: "10 Minutes",
    format: "MCQs",
    link: "/assessment/machine-learning",
  },
];
